name: CI
on: push
jobs:
  crystal-style:
    uses: PlaceOS/.github/.github/workflows/crystal-style.yml@main

  test:
    name: "crystal: ${{ matrix.crystal }}"
    strategy:
      fail-fast: false
      matrix:
        crystal:
          - latest
    runs-on: ubuntu-latest
    steps:
      - uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - uses: actions/checkout@v3
      - run: shards install --skip-postinstall --skip-executables
      - run: crystal spec --error-trace -v --order=random
