name: CI
on:
  push:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight
jobs:
  crystal-style:
    uses: PlaceOS/.github/.github/workflows/crystal-style.yml@main

  test:
    strategy:
      fail-fast: false
      matrix:
        crystal:
          - latest
          - nightly
    runs-on: ubuntu-latest
    steps:
      - uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - uses: actions/checkout@v2
      - run: shards install --skip-postinstall --skip-executables
      - run: crystal spec --error-trace -v --order=random
